name: Readme Template
on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at 5:30 am IST
#   push:
#     branches: [ main ]
jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: 0
#     - name: Generate README.md
#       uses: probablykasper/readme-template-action@v1
#       with:
#         token: ${{ secrets.README_TEMPLATE_TOKEN }}
#         template: TEMPLATE.md
#         output: README.md
#     - name: Update README.md
#       run: |
#         if [[ "$(git status --porcelain)" != "" ]]; then
#           git config user.name "GitHub Action"
#           git config user.email "action@github.com"
#           git add .
#           git commit -m "Auto-update README.md"
#           git push
#         fi
  list-repos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.7.0
    - run: node ./list.js
#     - run: npm test
    
